#pragma once
typedef enum DataTypeEnum
{
    Invalid = 0,
    Byte,
    Ascii,
    Short,
    Long,
    Rational,
    Sbyte,
    Undefined,
    Sshort,
    Slong,
    Srational,
    Float,
    Double,
    IFD,
} DataTypeEnum;
struct DataType
{
    DataTypeEnum type;
    int size;
};
struct TagType
{
    TagTypeEnum type;
    int id;
    DataTypeEnum dataType;
};
const DataType DataTypeList[] = {
    {DataTypeEnum::Invalid,0},// Should not be used
    {Byte,1},// 8-bit unsigned
    {Ascii,1},// 7-bit ASCII code
    {Short,2},// 16-bit unsigned
    {Long,4},// 32-bit unsigned
    {Rational,8},// 2 Longs, numerator:denominator
    {Sbyte,1},// 8 bit signed integer
    {Undefined,1},// 8 bit byte containing anything
    {Sshort,2},// 16 bit signed
    {Slong,4},// 32 bit signed
    {Srational,8},// 2 Slongs, numerator:denominator
    {Float,4},// 32bit float IEEE
    {Double,8},// 64bit double IEEE
    {IFD,4},// IFD (Same as Long)
};
typedef enum TagTypeEnum
{
    Invalid = 0,
    NewSubfileType,
    ImageWidth,
    ImageLength,
    BitsPerSample,
    Compression,
    PhotometricInterpretation,
    FillOrder,
    ImageDescription,
    Make,
    Model,
    StripOffsets,
    Orientation,
    SamplesPerPixel,
    RowsPerStrip,
    StripByteCounts,
    XResolution,
    YResolution,
    PlanarConfiguration,
    ResolutionUnit,
    Software,
    DateTime,
    Artist,
    Predictor,
    TileWidth,
    TileLength,
    TileOffsets,
    TileByteCounts,
    SubIFD,
    XMP_Metadata,
    CFARepeatPatternDim,
    CFAPattern,
    Copyright,
    ExposureTime,
    FNumber,
    EXIF_IFD,
    ExposureProgram,
    PhotographicSensitivity,
    SensitivityType,
    ExifVersion,
    DateTimeOriginal,
    ShutterSpeedValue,
    ApertureValue,
    ExposureBiasValue,
    MaxApertureValue,
    SubjectDistance,
    MeteringMode,
    Flash,
    FocalLength,
    TIFF_EP_StandardID,
    SubsecTime,
    SubsecTimeOriginal,
    FocalPlaneXResolution,
    FocalPlaneYResolution,
    FocalPlaneResolutionUnit,
    FocalLengthIn35mmFilm,
    EXIFPhotoBodySerialNumber,
    EXIFPhotoLensModel,
    DNGVersion,
    DNGBackwardVersion,
    UniqueCameraModel,
    CFAPlaneColor,
    CFALayout,
    LinearizationTable,
    BlackLevelRepeatDim,
    BlackLevel,
    WhiteLevel,
    DefaultScale,
    DefaultCropOrigin,
    DefaultCropSize,
    ColorMatrix1,
    ColorMatrix2,
    CameraCalibration1,
    CameraCalibration2,
    AnalogBalance,
    AsShotNeutral,
    BaselineExposure,
    BaselineNoise,
    BaselineSharpness,
    BayerGreenSplit,
    LinearResponseLimit,
    CameraSerialNumber,
    AntiAliasStrength,
    ShadowScale,
    DNGPrivateData,
    MakerNoteSafety,
    CalibrationIlluminant1,
    CalibrationIlluminant2,
    BestQualityScale,
    RawDataUniqueID,
    ActiveArea,
    CameraCalibrationSignature,
    ProfileCalibrationSignature,
    NoiseReductionApplied,
    ProfileName,
    ProfileHueSatMapDims,
    ProfileHueSatMapData1,
    ProfileHueSatMapData2,
    ProfileToneCurve,
    ProfileEmbedPolicy,
    ForwardMatrix1,
    ForwardMatrix2,
    PreviewApplicationName,
    PreviewApplicationVersion,
    PreviewSettingsDigest,
    PreviewColorSpace,
    PreviewDateTime,
    NoiseProfile,
    TimeCodes,
    FrameRate,
    OpcodeList1,
    OpcodeList2,
    ReelName,
    BaselineExposureOffset,
    DefaultBlackRender,
    NewRawImageDigest
} TagTypeEnum;

const TagType TagTypeList[] = {
    {TagTypeEnum::Invalid       ,0, DataTypeEnum::Invalid},
    {NewSubfileType             ,254,Long},
    {ImageWidth                 ,256,Long},
    {ImageLength                ,257,Long},
    {BitsPerSample              ,258,Short},
    {Compression                ,259,Short},
    {PhotometricInterpretation  ,262,Short},
    {FillOrder                  ,266,Short},
    {ImageDescription           ,270,Ascii},
    {Make                       ,271,Ascii},
    {Model                      ,272,Ascii},
    {StripOffsets               ,273,Long},
    {Orientation                ,274,Short},
    {SamplesPerPixel            ,277,Short},
    {RowsPerStrip               ,278,Short},
    {StripByteCounts            ,279,Long},
    {XResolution                ,282,Rational},
    {YResolution                ,283,Rational},
    {PlanarConfiguration        ,284,Short},
    {ResolutionUnit             ,296,Short},
    {Software                   ,305,Ascii},
    {DateTime                   ,306,Ascii},
    {Artist                     ,315,Ascii},
    {Predictor                  ,317,Short},
    {TileWidth                  ,322,Short},
    {TileLength                 ,323,Short},
    {TileOffsets                ,324,Long},
    {TileByteCounts             ,325,Long},
    {SubIFD                     ,330,IFD},
    {XMP_Metadata               ,700,Undefined},
    {CFARepeatPatternDim        ,33421,Short},
    {CFAPattern                 ,33422,Byte},
    {Copyright                  ,33432,Ascii},
    {ExposureTime               ,33434,Rational},
    {FNumber                    ,33437,Rational},
    {EXIF_IFD                   ,34665,IFD},
    {ExposureProgram            ,34850,Short},
    {PhotographicSensitivity    ,34855,Short},
    {SensitivityType            ,34864,Short},
    {ExifVersion                ,36864,Undefined},
    {DateTimeOriginal           ,36867,Ascii},
    {ShutterSpeedValue          ,37377,Srational},
    {ApertureValue              ,37378,Rational},
    {ExposureBiasValue          ,37380,Srational},
    {MaxApertureValue           ,37381,Rational},
    {SubjectDistance            ,37382,Rational},
    {MeteringMode               ,37383,Short},
    {Flash                      ,37385,Short},
    {FocalLength                ,37386,Rational},
    {TIFF_EP_StandardID         ,37398,Byte},
    {SubsecTime                 ,37520,Ascii},
    {SubsecTimeOriginal         ,37521,Ascii},
    {FocalPlaneXResolution      ,41486,Rational},
    {FocalPlaneYResolution      ,41487,Rational},
    {FocalPlaneResolutionUnit   ,41488,Short},
    {FocalLengthIn35mmFilm      ,41989,Short},
    {EXIFPhotoBodySerialNumber  ,42033,Ascii},
    {EXIFPhotoLensModel         ,42036,Ascii},
    {DNGVersion                 ,50706,Byte},
    {DNGBackwardVersion         ,50707,Byte},
    {UniqueCameraModel          ,50708,Ascii},
    {CFAPlaneColor              ,50710,Byte},
    {CFALayout                  ,50711,Short},
    {LinearizationTable         ,50712,Short},
    {BlackLevelRepeatDim        ,50713,Short},
    {BlackLevel                 ,50714,Short},
    {WhiteLevel                 ,50717,Short},
    {DefaultScale               ,50718,Rational},
    {DefaultCropOrigin          ,50719,Long},
    {DefaultCropSize            ,50720,Long},
    {ColorMatrix1               ,50721,Srational},
    {ColorMatrix2               ,50722,Srational},
    {CameraCalibration1         ,50723,Srational},
    {CameraCalibration2         ,50724,Srational},
    {AnalogBalance              ,50727,Rational},
    {AsShotNeutral              ,50728,Rational},
    {BaselineExposure           ,50730,Srational},
    {BaselineNoise              ,50731,Rational},
    {BaselineSharpness          ,50732,Rational},
    {BayerGreenSplit            ,50733,Long},
    {LinearResponseLimit        ,50734,Rational},
    {CameraSerialNumber         ,50735,Ascii},
    {AntiAliasStrength          ,50738,Rational},
    {ShadowScale                ,50739,Rational},
    {DNGPrivateData             ,50740,Byte},
    {MakerNoteSafety            ,50741,Short},
    {CalibrationIlluminant1     ,50778,Short},
    {CalibrationIlluminant2     ,50779,Short},
    {BestQualityScale           ,50780,Rational},
    {RawDataUniqueID            ,50781,Byte},
    {ActiveArea                 ,50829,Long},
    {CameraCalibrationSignature ,50931,Ascii},
    {ProfileCalibrationSignature,50932,Ascii},
    {NoiseReductionApplied      ,50935,Rational},
    {ProfileName                ,50936,Ascii},
    {ProfileHueSatMapDims       ,50937,Long},
    {ProfileHueSatMapData1      ,50938,Float},
    {ProfileHueSatMapData2      ,50939,Float},
    {ProfileToneCurve           ,50940,Float},
    {ProfileEmbedPolicy         ,50941,Long},
    {ForwardMatrix1             ,50964,Srational},
    {ForwardMatrix2             ,50965,Srational},
    {PreviewApplicationName     ,50966,Ascii},
    {PreviewApplicationVersion  ,50967,Ascii},
    {PreviewSettingsDigest      ,50969,Byte},
    {PreviewColorSpace          ,50970,Long},
    {PreviewDateTime            ,50971,Ascii},
    {NoiseProfile               ,51041,Double},
    {TimeCodes                  ,51043,Byte},
    {FrameRate                  ,51044,Srational},
    {OpcodeList1                ,51008,Undefined},
    {OpcodeList2                ,51009,Undefined},
    {ReelName                   ,51081,Ascii},
    {BaselineExposureOffset     ,51109,Srational},
    {DefaultBlackRender         ,51110,Long},
    {NewRawImageDigest          ,51111,Byte}
};