let DataType = {
    Invalid:[0,0],// Should not be used
    Byte:[1,1],// 8-bit unsigned
    Ascii:[2,1],// 7-bit ASCII code
    Short:[3,2],// 16-bit unsigned
    Long:[4,4],// 32-bit unsigned
    Rational:[5,8],// 2 Longs, numerator:denominator
    Sbyte:[6,1],// 8 bit signed integer
    Undefined:[7,1],// 8 bit byte containing anything
    Sshort:[8,2],// 16 bit signed
    Slong:[9,4],// 32 bit signed
    Srational:[10,8],// 2 Slongs, numerator:denominator
    Float:[11,4],// 32bit float IEEE
    Double:[12,8],// 64bit double IEEE
    IFD:[13,4],// IFD (Same as Long)
};
let TagType = {
    Invalid                    :[0,DataType.Invalid],
    NewSubfileType             :[254,DataType.Long],
    ImageWidth                 :[256,DataType.Long],
    ImageLength                :[257,DataType.Long],
    BitsPerSample              :[258,DataType.Short],
    Compression                :[259,DataType.Short],
    PhotometricInterpretation  :[262,DataType.Short],
    FillOrder                  :[266,DataType.Short],
    ImageDescription           :[270,DataType.Ascii],
    Make                       :[271,DataType.Ascii],
    Model                      :[272,DataType.Ascii],
    StripOffsets               :[273,DataType.Long],
    Orientation                :[274,DataType.Short],
    SamplesPerPixel            :[277,DataType.Short],
    RowsPerStrip               :[278,DataType.Short],
    StripByteCounts            :[279,DataType.Long],
    XResolution                :[282,DataType.Rational],
    YResolution                :[283,DataType.Rational],
    PlanarConfiguration        :[284,DataType.Short],
    ResolutionUnit             :[296,DataType.Short],
    Software                   :[305,DataType.Ascii],
    DateTime                   :[306,DataType.Ascii],
    Artist                     :[315,DataType.Ascii],
    Predictor                  :[317,DataType.Short],
    TileWidth                  :[322,DataType.Short],
    TileLength                 :[323,DataType.Short],
    TileOffsets                :[324,DataType.Long],
    TileByteCounts             :[325,DataType.Long],
    SubIFD                     :[330,DataType.IFD],
    XMP_Metadata               :[700,DataType.Undefined],
    CFARepeatPatternDim        :[33421,DataType.Short],
    CFAPattern                 :[33422,DataType.Byte],
    Copyright                  :[33432,DataType.Ascii],
    ExposureTime               :[33434,DataType.Rational],
    FNumber                    :[33437,DataType.Rational],
    EXIF_IFD                   :[34665,DataType.IFD],
    ExposureProgram            :[34850,DataType.Short],
    PhotographicSensitivity    :[34855,DataType.Short],
    SensitivityType            :[34864,DataType.Short],
    ExifVersion                :[36864,DataType.Undefined],
    DateTimeOriginal           :[36867,DataType.Ascii],
    ShutterSpeedValue          :[37377,DataType.Srational],
    ApertureValue              :[37378,DataType.Rational],
    ExposureBiasValue          :[37380,DataType.Srational],
    MaxApertureValue           :[37381,DataType.Rational],
    SubjectDistance            :[37382,DataType.Rational],
    MeteringMode               :[37383,DataType.Short],
    Flash                      :[37385,DataType.Short],
    FocalLength                :[37386,DataType.Rational],
    TIFF_EP_StandardID         :[37398,DataType.Byte],
    SubsecTime                 :[37520,DataType.Ascii],
    SubsecTimeOriginal         :[37521,DataType.Ascii],
    FocalPlaneXResolution      :[41486,DataType.Rational],
    FocalPlaneYResolution      :[41487,DataType.Rational],
    FocalPlaneResolutionUnit   :[41488,DataType.Short],
    FocalLengthIn35mmFilm      :[41989,DataType.Short],
    EXIFPhotoBodySerialNumber  :[42033,DataType.Ascii],
    EXIFPhotoLensModel         :[42036,DataType.Ascii],
    DNGVersion                 :[50706,DataType.Byte],
    DNGBackwardVersion         :[50707,DataType.Byte],
    UniqueCameraModel          :[50708,DataType.Ascii],
    CFAPlaneColor              :[50710,DataType.Byte],
    CFALayout                  :[50711,DataType.Short],
    LinearizationTable         :[50712,DataType.Short],
    BlackLevelRepeatDim        :[50713,DataType.Short],
    BlackLevel                 :[50714,DataType.Short],
    WhiteLevel                 :[50717,DataType.Short],
    DefaultScale               :[50718,DataType.Rational],
    DefaultCropOrigin          :[50719,DataType.Long],
    DefaultCropSize            :[50720,DataType.Long],
    ColorMatrix1               :[50721,DataType.Srational],
    ColorMatrix2               :[50722,DataType.Srational],
    CameraCalibration1         :[50723,DataType.Srational],
    CameraCalibration2         :[50724,DataType.Srational],
    AnalogBalance              :[50727,DataType.Rational],
    AsShotNeutral              :[50728,DataType.Rational],
    BaselineExposure           :[50730,DataType.Srational],
    BaselineNoise              :[50731,DataType.Rational],
    BaselineSharpness          :[50732,DataType.Rational],
    BayerGreenSplit            :[50733,DataType.Long],
    LinearResponseLimit        :[50734,DataType.Rational],
    CameraSerialNumber         :[50735,DataType.Ascii],
    AntiAliasStrength          :[50738,DataType.Rational],
    ShadowScale                :[50739,DataType.Rational],
    DNGPrivateData             :[50740,DataType.Byte],
    MakerNoteSafety            :[50741,DataType.Short],
    CalibrationIlluminant1     :[50778,DataType.Short],
    CalibrationIlluminant2     :[50779,DataType.Short],
    BestQualityScale           :[50780,DataType.Rational],
    RawDataUniqueID            :[50781,DataType.Byte],
    ActiveArea                 :[50829,DataType.Long],
    CameraCalibrationSignature :[50931,DataType.Ascii],
    ProfileCalibrationSignature:[50932,DataType.Ascii],
    NoiseReductionApplied      :[50935,DataType.Rational],
    ProfileName                :[50936,DataType.Ascii],
    ProfileHueSatMapDims       :[50937,DataType.Long],
    ProfileHueSatMapData1      :[50938,DataType.Float],
    ProfileHueSatMapData2      :[50939,DataType.Float],
    ProfileToneCurve           :[50940,DataType.Float],
    ProfileEmbedPolicy         :[50941,DataType.Long],
    ForwardMatrix1             :[50964,DataType.Srational],
    ForwardMatrix2             :[50965,DataType.Srational],
    PreviewApplicationName     :[50966,DataType.Ascii],
    PreviewApplicationVersion  :[50967,DataType.Ascii],
    PreviewSettingsDigest      :[50969,DataType.Byte],
    PreviewColorSpace          :[50970,DataType.Long],
    PreviewDateTime            :[50971,DataType.Ascii],
    NoiseProfile               :[51041,DataType.Double],
    TimeCodes                  :[51043,DataType.Byte],
    FrameRate                  :[51044,DataType.Srational],
    OpcodeList1                :[51008,DataType.Undefined],
    OpcodeList2                :[51009,DataType.Undefined],
    ReelName                   :[51081,DataType.Ascii],
    BaselineExposureOffset     :[51109,DataType.Srational],
    DefaultBlackRender         :[51110,DataType.Long],
    NewRawImageDigest          :[51111,DataType.Byte]
}
module.exports = {TagType,DataType}